"""empty message

Revision ID: 8ba7ce802b23
Revises: 0b6a648591ba
Create Date: 2025-03-31 15:52:13.180799

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8ba7ce802b23'
down_revision = '0b6a648591ba'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('people', schema=None) as batch_op:
        batch_op.drop_constraint('people_favorites_user_fkey', type_='foreignkey')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('people', schema=None) as batch_op:
        batch_op.create_foreign_key('people_favorites_user_fkey', 'planets', ['favorites_user'], ['id'])

    # ### end Alembic commands ###
