"""empty message

Revision ID: a44bdfc9a4c6
Revises: 1eebcfcdd527
Create Date: 2025-04-03 03:15:31.018358

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a44bdfc9a4c6'
down_revision = '1eebcfcdd527'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('people', schema=None) as batch_op:
        batch_op.drop_column('favorites_user')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('people', schema=None) as batch_op:
        batch_op.add_column(sa.Column('favorites_user', sa.INTEGER(), autoincrement=False, nullable=False))

    # ### end Alembic commands ###
